#!/bin/sh

_util-say()
{
    local cur prev words cword
    _init_completion -n = 2>/dev/null
    
    COMPREPLY=( $( compgen -W `util-say --list` -- "$cur" ) )
}

complete -o default -F _util-say util-say
